- hosts: elastic
  remote_user: seregin
  become: yes
  tasks:
  - name: uploading elasticsearch
    copy:
      src: /tmp/ansible/elasticsearch/elasticsearch-8.2.2-amd64.deb
      dest: /tmp
  - name: installing elasticsearch
    apt:
      deb: /tmp/elasticsearch-8.2.2-amd64.deb 
      state: present
