- hosts: kibana
  remote_user: seregin
  become: yes
  tasks:
  - name: uploading kibana
    copy:
      src: /tmp/ansible/elasticsearch/kibana-8.2.2-amd64.deb 
      dest: /tmp
  - name: installing elasticsearch
    apt:
      deb: /tmp/kibana-8.2.2-amd64.deb 
      state: present
